### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by FerPapi** [permitio/fastapi_websocket_pubsub#35]
Hey guys, thanks for the fantastic work.

I've encountered a timeout error, but nowhere in the docs or source code I found how to set a limit (if possible at all) for the client. My server consumes an awaitable function that provides data at 1 minute intervals. The server then publishes the data. But the client times out at what it seems like 5 seconds

```
RPC Error
Traceback (most recent call last):
  File "/home/fernandopapi/.cache/pypoetry/virtualenvs/propdesk-ml-ops-nZ04QmJs-py3.8/lib/python3.8/site-packages/fastapi_websocket_rpc/websocket_rpc_client.py", line 118, in __connect__
    raw_ws = await self.conn.__aenter__()
  File "/home/fernandopapi/.cache/pypoetry/virtualenvs/propdesk-ml-ops-nZ04QmJs-py3.8/lib/python3.8/site-packages/websockets/legacy/client.py", line 633, in __aenter__
    return await self
  File "/home/fernandopapi/.cache/pypoetry/virtualenvs/propdesk-ml-ops-nZ04QmJs-py3.8/lib/python3.8/site-packages/websockets/legacy/client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```

Can I set this TimeOut limit? Thanks!

**Comment by orweis** [comment]
Hi @FerPapi !
Thanks for the kind words.

As you can see in:
https://github.com/permitio/fastapi_websocket_rpc/blob/647c0b40ac443b82bb1edfea0f9552c2dbd82613/fastapi_websocket_rpc/websocket_rpc_client.py#L54

All the kwargs you pass are passed to the underlying Websocket connect function, as detailed here:

https://websockets.readthedocs.io/en/stable/reference/client.html#websockets.client.connect

Including the timeouts ;)

**Comment by FerPapi** [comment]
Oh, cool! Sorry I missed that. Thanks!
